services:
  fizzbuzz-service:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fizzbuzz-service
    ports:
      - '9000:9000'
  prometheus:
    image: prom/prometheus:v2.28.1
    restart: always
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

volumes:
  prometheus_data: